#!/usr/bin/env python

import mysql.connector
import sys
import traceback
import json


def get_flag(ip, port, flag_id, token):
	mydb = mysql.connector.connect(
		host=ip,
		user="out_test",
		password="123456",
		database="web"
	)

	mycursor = mydb.cursor()

	flag_id_edit = '"' + flag_id + '"'
	token_edit = '"' + token + '"'

	sql = "SELECT  tenmonthi FROM monthi WHERE idsv = %s AND %s" % (flag_id_edit, token_edit)

	mycursor.execute(sql)

	rel_flag = mycursor.fetchall()
	mydb.commit()

	response = {
		'error': 0,
		'error_msg': '',
		'payload': {
			'flag': rel_flag,
		}
	}
	return response

if __name__ == "__main__":
	try: 
		print (json.dumps(get_flag(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])))
	except Exception as e:
		response = {
			"error": "error" ,
			"error_msg": str(e) + "\n" + traceback.format_exc(),
			"payload": {}
		}
		print (json.dumps(response))


