service: 
	mkdir -p service/ro
	mkdir -p service/rw
	mkdir -p service/append
	cp -r ./src/examreg.com/* ./service/ro

bundle: 
	
scriptbot_scripts:
	docker build -t $(SERVICE_NAME)_scripts ./scripts


